yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'
urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('posts/', views.posts, name='posts'),
    ]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls)
]

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.TextField()
    slug = models.TextField()
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.CASCADE,
        blank=True, null=True
    )

yatube/posts/views.py
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from .models import Post, Group


def index(request):
    template = 'posts/index.html'
    title = "Это главная страница проекта Yatube"
    posts = Post.objects.order_by('-pub_date')[:10]
    context = {
        'posts': posts,
        'title': title,
    }
    return render(request, template, context)


def group_posts(request, slug):
    template = 'posts/group_list.html'
    title = "Здесь будет информация о группах проекта Yatube"
    group = get_object_or_404(Group, slug=slug)

    posts = Post.objects.filter(group=group).order_by('-pub_date')[:10]
    context = {
        'group': group,
        'posts': posts,
        'title': title,
    }
    return render(request, template, context)


def posts(request):
    return HttpResponse(200)

yatube/templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="ru">
  <head>
    {% load static %}
    <img src="{% static 'img/logo.png' %}" />
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <meta charset="utf-8" />
    <!-- Кодировка сайта -->
    <!-- Сайт готов работать с мобильными устройствами -->
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <!-- Загружаем фав-иконки -->
    <link rel="icon" href="img/fav/fav.ico" type="image" />
    <link
      rel="apple-touch-icon"
      sizes="180x180"
      href="img/fav/apple-touch-icon.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="32x32"
      href="img/fav/favicon-32x32.png"
    />
    <link
      rel="icon"
      type="image/png"
      sizes="16x16"
      href="img/fav/favicon-16x16.png"
    />
    <meta name="msapplication-TileColor" content="#000" />
    <meta name="theme-color" content="#ffffff" />
    <!-- Подключен файл со стандартными стилями бустрап -->
    <link rel="stylesheet" href="css/bootstrap.min.css" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% include 'includes/header.html' %}
    <main>{% block content %} Контент не подвезли :( {% endblock %}</main>
    {% include 'includes/footer.html' %}
  </body>
</html>

yatube/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <!-- тег span используется для добавления нужных стилей отдельным участкам текста --> 
    <p>© 2020 Copyright <span style="color:red">Ya</span>tube</p>    
  </footer>

yatube/templates/includes/header.html
<header>
    <!-- Использованы классы бустрапа для создания типовой навигации с логотипом -->
    <!-- В дальнейшем тут будет создано полноценное меню -->
    <nav class="navbar navbar-light" style="background-color: lightskyblue">
      <div class="container">
        <a class="navbar-brand" href="{% url 'posts:index'%}">
          <img src="img/logo.png" width="30" height="30" class="d-inline-block align-top" alt="">
          <!-- тег span используется для добавления нужных стилей отдельным участкам текста -->
          <span style="color:red">Ya</span>tube
        </a>
      </div>
    </nav>      
  </header>

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
    <main>
      <!-- класс py-5 создает отступы сверху и снизу блока -->
      <div class="container py-5">
        {% comment %} <h1>Лев Толстой – зеркало русской революции.</h1>
        <p>
          Группа тайных поклонников графа.
        </p> {% endcomment %}
        {% for post in posts %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
          {% if post.group %}   
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %} #добвил груп
      <p>{{ post.text }}</p>    
      <a href="">все записи группы</a>
      {% if not forloop.last %}<hr>{% endif %} 
    </article>
        <!-- под последним постом нет линии -->
      </div>  
    </main>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %} {{ title }} {% endblock %}
{% block content %}
<main> 
  <!-- класс py-5 создает отступы сверху и снизу блока -->
  <div class="container py-5">     
    <h1>Последние обновления на сайте</h1>
      {% for post in posts %}
      <article>
        <ul>
          <li>
            Автор: {{ post.author.get_full_name }}
          </li>
          <li>
            Дата публикации: {{ post.pub_date|date:"d E Y" }}
          </li>
        </ul>
          {% if post.group %}   
          <a href="{% url 'posts:group_list' post.group.slug %}">все записи группы</a>
        {% endif %}
      <p>{{ post.text }}</p>    
      <a href="">все записи группы</a>
      {% if not forloop.last %}<hr>{% endif %} 
    </article>
    {% endfor %}
    <!-- под последним постом нет линии -->
  </div>  
</main>
{% endblock %} 